language: c
compiler:
  - gcc
  - clang
before_install:
    - sudo apt-get -qq update
install:
    - sudo apt-get -qq install rake bison git gperf
before_script:
  - git clone https://github.com/mruby/mruby.git ../mruby
  - cd ../mruby
  - cp -fp ../mruby-clamav/build_config.rb build_config.rb
script:
  - make all test
